-- Idempotent migration for the single Supabase table used by the app.
-- The frontend reads and writes only public.hopes_corner_leaderboard.

create table if not exists public.hopes_corner_leaderboard (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score integer not null check (score >= 0),
  created_at timestamptz not null default timezone('utc'::text, now())
);

grant usage on schema public to anon;
grant select (player_name, score), insert (player_name, score) on public.hopes_corner_leaderboard to anon;

do $$
declare
  id_sequence text;
begin
  id_sequence := pg_get_serial_sequence('public.hopes_corner_leaderboard', 'id');

  if id_sequence is not null then
    execute format('grant usage, select on sequence %s to anon', id_sequence);
  end if;
end
$$;

alter table public.hopes_corner_leaderboard enable row level security;

do $$
declare
  existing record;
begin
  select
    p.polcmd,
    coalesce(array_agg(r.rolname::text order by r.rolname::text) filter (where r.rolname is not null), array[]::text[]) as roles,
    regexp_replace(coalesce(pg_get_expr(p.polqual, p.polrelid), ''), '\s+', ' ', 'g') as using_expr,
    regexp_replace(coalesce(pg_get_expr(p.polwithcheck, p.polrelid), ''), '\s+', ' ', 'g') as with_check_expr
  into existing
  from pg_policy p
  left join pg_roles r on r.oid = any (p.polroles)
  where p.polrelid = 'public.hopes_corner_leaderboard'::regclass
    and p.polname = 'leaderboard_select_anon'
  group by p.polcmd, p.polqual, p.polwithcheck, p.polrelid;

  if not found
    or existing.polcmd <> 'r'
    or existing.roles <> array['anon']::text[]
    or existing.using_expr <> 'true'
    or existing.with_check_expr <> '' then
    drop policy if exists leaderboard_select_anon on public.hopes_corner_leaderboard;

    create policy leaderboard_select_anon
      on public.hopes_corner_leaderboard
      for select
      to anon
      using (true);
  end if;
end
$$;

do $$
declare
  existing record;
begin
  select
    p.polcmd,
    coalesce(array_agg(r.rolname::text order by r.rolname::text) filter (where r.rolname is not null), array[]::text[]) as roles,
    regexp_replace(coalesce(pg_get_expr(p.polqual, p.polrelid), ''), '\s+', ' ', 'g') as using_expr,
    regexp_replace(coalesce(pg_get_expr(p.polwithcheck, p.polrelid), ''), '\s+', ' ', 'g') as with_check_expr
  into existing
  from pg_policy p
  left join pg_roles r on r.oid = any (p.polroles)
  where p.polrelid = 'public.hopes_corner_leaderboard'::regclass
    and p.polname = 'leaderboard_insert_anon'
  group by p.polcmd, p.polqual, p.polwithcheck, p.polrelid;

  if not found
    or existing.polcmd <> 'a'
    or existing.roles <> array['anon']::text[]
    or existing.using_expr <> ''
    or existing.with_check_expr !~ 'score\s*>=\s*0'
    or existing.with_check_expr !~ 'char_length\(btrim\(player_name\)\)\s*>=\s*1'
    or existing.with_check_expr !~ 'char_length\(player_name\)\s*<=\s*50' then
    drop policy if exists leaderboard_insert_anon on public.hopes_corner_leaderboard;

    create policy leaderboard_insert_anon
      on public.hopes_corner_leaderboard
      for insert
      to anon
      with check (
        score >= 0
        and char_length(btrim(player_name)) >= 1
        and char_length(player_name) <= 50
      );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_indexes
    where schemaname = 'public'
      and tablename = 'hopes_corner_leaderboard'
      and indexdef ilike '%(score DESC)%'
  ) then
    create index if not exists hopes_corner_leaderboard_score_desc_idx
      on public.hopes_corner_leaderboard (score desc);
  end if;
end
$$;
